export const mobileNavClasses = {
  header: "fixed left-0 right-0 top-0 z-50 border-b border-sidebar-border bg-sidebar md:hidden",
  headerContent: "flex items-center justify-between px-4 py-3",
  brandLink: "flex items-center gap-2",
  brandIconWrapper:
    "icon-parent flex h-8 w-8 items-center justify-center rounded-lg bg-sidebar-primary",
  brandIcon: "icon-nonessential h-5 w-5 text-primary-foreground",
  brandText: "font-display text-lg font-semibold text-sidebar-foreground",
  menuButton: "text-sidebar-foreground",
  menuIcon: "h-6 w-6",
  sheetContent: "w-72 border-sidebar-border bg-sidebar p-0",
  sheetHeader: "border-b border-sidebar-border p-4",
  sheetTitle: "flex items-center gap-2 text-sidebar-foreground",
  navContainer: "flex h-[calc(100%-65px)] flex-col p-4",
  nav: "flex-1 space-y-1",
  navItemBase:
    "flex items-center gap-3 rounded-xl px-4 py-3 text-sidebar-foreground transition-all",
  navItemActive: "bg-sidebar-primary text-sidebar-primary-foreground",
  navItemDefault: "hover:bg-sidebar-accent hover:text-sidebar-accent-foreground",
  navItemIcon: "icon-nonessential h-5 w-5",
  navItemLabel: "font-medium",
  footer: "space-y-3 border-t border-sidebar-border pt-4",
  userInfo: "rounded-xl border border-sidebar-border/60 bg-sidebar-accent/30 px-3 py-2",
  userName: "truncate text-sm font-medium text-sidebar-foreground",
  userEmail: "truncate text-xs text-muted-foreground",
  logoutButton:
    "flex items-center gap-3 w-full rounded-xl border border-sidebar-border bg-sidebar px-3 py-2 text-sm font-medium text-sidebar-foreground transition-colors hover:bg-sidebar-accent cursor-pointer",
  footerText: "text-center text-xs text-muted-foreground",
  srOnly: "sr-only",
} as const;
