export const pomodoroTimerClasses = {
  root: "flex flex-col items-center",
  clockWrapper: "relative mb-8",
  svg: "h-72 w-72 -rotate-90",
  centerContent: "absolute inset-0 flex flex-col items-center justify-center",
  phaseIconWrapper: "mb-2",
  phaseIcon: "h-8 w-8",
  phaseLabel: "mb-1 text-sm font-medium",
  time: "font-display tabular-nums text-5xl font-bold text-foreground",
  cycleCounter: "mt-2 text-sm text-muted-foreground",
  actions: "flex items-center gap-4",
  startButton: "mindease-button-primary px-8",
  startButtonIcon: "mr-2 h-5 w-5",
  sideButton: "h-12 w-12 rounded-xl",
  primaryToggleButton: "h-14 w-14 rounded-2xl",
  runningToggleButton: "bg-destructive hover:bg-destructive/90",
  pausedToggleButton: "mindease-button-primary",
  largeIcon: "h-6 w-6",
  playOffsetIcon: "ml-0.5 h-6 w-6",
  smallIcon: "h-5 w-5",
  indicators: "mt-8 flex gap-2",
  indicatorBase: "h-2.5 w-2.5 rounded-full transition-colors",
  indicatorDone: "bg-primary",
  indicatorPending: "bg-muted",
  footerText: "mt-3 text-sm text-muted-foreground",
} as const;
