export const taskCardClasses = {
  content: "flex items-start gap-3",
  dragHandle: "cursor-grab opacity-0 transition-opacity group-hover:opacity-100",
  dragIcon: "h-5 w-5 text-muted-foreground",
  body: "min-w-0 flex-1",
  header: "mb-2 flex items-start justify-between gap-2",
  description: "task-card-description mb-3 line-clamp-2 text-sm text-muted-foreground",
  checklist: "task-card-checklist mb-3 space-y-2",
  checklistItem: "flex items-center gap-2",
  checklistCheckbox: "h-4 w-4",
  checklistLabelBase: "cursor-pointer text-sm",
  checklistLabelDone: "line-through text-muted-foreground",
  checklistLabelPending: "text-foreground",
  hiddenCount: "task-card-hidden-count text-xs text-muted-foreground",
  progressTrack: "task-card-progress h-1.5 overflow-hidden rounded-full bg-muted",
  progressFill: "h-full rounded-full bg-success",
  footer: "task-card-footer flex items-center justify-between border-t border-border pt-2",
  estimate: "task-card-estimate flex items-center gap-1 text-xs text-muted-foreground",
  estimateIcon: "h-3.5 w-3.5",
  actionIcon: "h-3.5 w-3.5",
} as const;
